### ISSUE TITLE
How can I set advanced configuration options?

### ISSUE THREAD

**Issue by viraj-khatavkar** [chairuosen/vue2-ace-editor#1]
I need to set the following configuration option:

```javascript
editor.setShowPrintMargin(false);
```

**Comment by chairuosen** [comment]
@viraj-khatavkar Install version 0.0.2 and now you can get the AceEditor object in init function

```
<editor @init="editorInit"></editor>
```

```
methods:{
    editorInit:function(editor){
         //todo
    }
}
```

**Comment by chairuosen** [comment]
@viraj-khatavkar can u show me a demo about the error

**Comment by viraj-khatavkar** [comment]
```javascript
editorInit(editor) {
            console.log(editor);
            editor.setShowPrintMargin(false);
            require('../../../../../node_modules/brace/mode/html');
            require('../../../../../node_modules/brace/mode/javascript');
            require('../../../../../node_modules/brace/mode/less');
            require('../../../../../node_modules/brace/theme/chrome');
        }
```

I get undefined in console..

**Comment by chairuosen** [comment]
@viraj-khatavkar ok.It prints undefined in console but not an error, right?
Make sure the version is 0.0.2 and call methed in html like this `@init="editorInit"` not this `@init="editorInit();"`

**Comment by viraj-khatavkar** [comment]
@chairuosen ah, okay.. I got that right. There is an another console error I am facing as below:

![screen shot 2016-11-29 at 8 14 02 pm](https://cloud.githubusercontent.com/assets/5693836/20714002/809d8386-b670-11e6-8187-adca2f718010.png)

**Comment by chairuosen** [comment]
@viraj-khatavkar Well...This seems not mine. Try force reload the page?

**Comment by viraj-khatavkar** [comment]
@chairuosen Done already, but if I click on index.js in the second line of above error it shows following

![screen shot 2016-11-29 at 8 21 31 pm](https://cloud.githubusercontent.com/assets/5693836/20714260/7109a85e-b671-11e6-8e99-f2491a99ff94.png)

**Comment by chairuosen** [comment]
@viraj-khatavkar yeah, this is my code. and it will load emmet module by async request. 
Does the error show again?

**Comment by viraj-khatavkar** [comment]
@chairuosen  Yes, it shows that always :)

**Comment by chairuosen** [comment]
@viraj-khatavkar Please check the network panel in chrome console.
It should be a bundle.js request like `app-xxxxxxx.js` and a chunk request like `1.1.xxxxx.js`. Does the chunk load successfully?

**Comment by viraj-khatavkar** [comment]
Nope, it doesn't:

![screen shot 2016-11-29 at 8 38 09 pm](https://cloud.githubusercontent.com/assets/5693836/20715000/c895d4d8-b673-11e6-8686-4c8f1409f24a.png)

**Comment by chairuosen** [comment]
@viraj-khatavkar Well. I got no error in my test demo. Can you creat a smallest repo that reproduce this error.
