### ISSUE TITLE
输入中文时有问题

### ISSUE THREAD

**Issue by wang30** [chairuosen/vue2-ace-editor#10]

**Comment by chairuosen** [comment]
抱歉无法处理ACE编辑器里的问题，可以去ACE的repo里提issue

**Comment by wang30** [comment]
好像ace新版本里面修复了，然后应该是你那需要更新一下吧

**Comment by chairuosen** [comment]
@wang30 可以给个链接么？我看看。

**Comment by wang30** [comment]
https://github.com/ajaxorg/ace/issues/3119

**Comment by chairuosen** [comment]
@wang30 我把brace升到0.11.0了，试了下应该是可以了，你重新安装下试试。

**Comment by wang30** [comment]
好了，谢谢大佬

**Comment by yunhongyao** [comment]
太感谢大佬了

**Comment by phymo** [comment]
IE 里面使用微软输入法的时候，还是有问题。。。
