### ISSUE TITLE
Error in example

### ISSUE THREAD

**Issue by larsmars** [chairuosen/vue2-ace-editor#11]
Hi,

After running:

> npm install --save-dev vue2-ace-editor

![ace](https://user-images.githubusercontent.com/5154589/35959081-469214e6-0ca4-11e8-86d4-e7da716476f3.PNG)

```
        editorInit:function () {
            require('vue-ace-editor/node_modules/brace/mode/html');
            require('vue-ace-editor/node_modules/brace/mode/javascript');
            require('vue-ace-editor/node_modules/brace/mode/less');
            require('vue-ace-editor/node_modules/brace/theme/chrome');
        }
```

This is not working.
Module not found Error: Can`t resolve 'vue-ace-editor/node_modules/brace/mode/html' 
(same for all 4)

Require brace in package.json 

`  "brace": "^0.11.0",`

And use this:

```
    editorInit: function (editor) {
      require('brace/mode/html')
      require('brace/mode/javascript')
      require('brace/mode/less')
      require('brace/theme/chrome')
    }
```

**Comment by chairuosen** [comment]
Well. yes u are right. The actual dir depends on your npm version.
