### ISSUE TITLE
Consider to be eslint compliant (typo)

### ISSUE THREAD

**Issue by larsmars** [chairuosen/vue2-ace-editor#12]
Consider to be eslint compliant for example code

1. Remove unnecessary: " ; " aka semicolon

2. Fix spacing:

@ editor:require('vue2-ace-editor'),
= editor: require('vue2-ace-editor'),

@ editorInit:function () {
= editorInit: function () {

**Comment by chairuosen** [comment]
There's no absolutely correct style for coding.

**Comment by larsmars** [comment]
Why make it harder for users? The suggested code change will not create any braking changes and will remove any lint problems for users who use ES Lint Standard.

**Comment by chairuosen** [comment]
@larsmars I think ES lint should only works for user's code. but not 3rd lib's.
you can put `node_modules/**` in the project's .eslintignore file

**Comment by chairuosen** [comment]
Yeah. I misread.
I dont think it is hard for a developer to find the code with ESLint warning by the ESLint he configured by himself.
But, as you wish, i will update the readme :)

**Comment by larsmars** [comment]
🌷 🌹
