### ISSUE TITLE
Optimize event handler on init

### ISSUE THREAD

**Issue by larsmars** [chairuosen/vue2-ace-editor#13]
`<editor v-model="content" @init="editorInit();" lang="html" theme="chrome" width="500" height="100"></editor>`

![ace_bug](https://user-images.githubusercontent.com/5154589/35960445-e94659ea-0ca9-11e8-82f6-28ed0af28ae5.PNG)

**Should be used as:**

`<editor v-model="content" @init="editorInit" lang="html" theme="chrome" width="500" height="100"></editor>`

If used this way the edior is available for configuration on init.
ie:

```
    editorInit: function (editor) {
      editor.setShowPrintMargin(false)
      require('brace/mode/html')
      require('brace/mode/python')
      require('brace/mode/less')
      require('brace/theme/monokai')
    }
```

"brace": "^0.11.0"
"vue2-ace-editor": "^0.0.4"
"vue": "^2.5.13"

**Comment by chairuosen** [comment]
forgot to update readme. fixed.

 Thank you~

**Comment by larsmars** [comment]
great stuff 👍
