### ISSUE TITLE
node_modules 没传上来报错了

### ISSUE THREAD

**Issue by cookieY** [chairuosen/vue2-ace-editor#15]
ERROR in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/Search/SearchSQL.vue
Module not found: Error: Can't resolve 'vue-ace-editor/node_modules/brace/mode/less'

**Comment by chairuosen** [comment]
这个模块地址是根据Npm版本不同位置不同的，Npm<3是树型结构的，大于3是水平结构。所以需要你自己看看项目根目录node_modules里有没有brace，改下目录
