### ISSUE TITLE
[Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'edit' of undefined"

### ISSUE THREAD

**Issue by cookieY** [chairuosen/vue2-ace-editor#16]
你好  按照说明文档 使用  但是遇到了

[Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'edit' of undefined"

这个问题 请问该如何解决 谢谢

**Comment by chairuosen** [comment]
重新安装一下brace试试。
如果还不行，说一下环境，是webpack打包的浏览器环境么？最好贴demo

**Comment by cookieY** [comment]
重装了还是不行 使用的是webpack vue是工程化的

**Comment by chairuosen** [comment]
试一下这个DEMO https://github.com/chairuosen/vue-ace-editor-demo/tree/vue2

**Comment by cookieY** [comment]
demo没有问题... 很是纳闷

**Comment by chairuosen** [comment]
你看一下你自己在代码里require('brace')得到什么？如果不是一个ace对象的话，可能brace安装有问题

**Comment by cookieY** [comment]
brace 安装了N遍 还是不行   - - 感觉是没有找到正确的包 我是直接写在.vue组件文件中的  是因为这个原因么

**Comment by chairuosen** [comment]
与.vue文件无关，我也是这么用的。
你可以做一个最小复现demo给我么？

**Comment by cookieY** [comment]
大大 可以加个联系方式么？ 详聊吗。这个问题搞了1天了 - - 还是一点头绪都没有

**Comment by cookieY** [comment]
@chairuosen 解决了，在新生成的脚手架项目里面就没有问题 估计是现有的项目脚手架配置问题。

**Comment by hash-bang** [comment]
I had the same issue. For anyone wanting a fix, the problem seems to be that Brace uses its own version of an ES6 require rather than the native.

Add:

```javascript
window.ace.acequire = window.ace.require;

```

...early in your load order to override its broken `acequire()` with the more standards compliant `require()`.
