### ISSUE TITLE
Error octal literal in strict mode

### ISSUE THREAD

**Issue by CrzKev** [chairuosen/vue2-ace-editor#17]
Hi,

When I add this component I got next error when building my project with electron builder.
Project is based on electron-vue(https://github.com/SimulatedGREG/electron-vue/issues/314) and the error is also mentioned over there. But it's somewhere in this component but I can't figure it out...

ERROR in unknown: Octal literal in strict mode (5457:23)

**Comment by chairuosen** [comment]
this error means there's an octal value in your code without prefix. but I dont have an octal value in my code. 
So can you debug the error with the feature `pause on exceptions` of chrome's devtool, you can easily got the breakpoint. and see what happened

**Comment by CrzKev** [comment]
This is the error I got maybe it has something to do with the webpack configuration I will search a little further.
![image](https://user-images.githubusercontent.com/33102056/36272651-699375e6-1282-11e8-93f9-d4aa17d72c1d.png)

**Comment by chairuosen** [comment]
solved@0.0.6
