### ISSUE TITLE
I cannot get this to work

### ISSUE THREAD

**Issue by dudesweet100** [chairuosen/vue2-ace-editor#2]
Can we get an example, where using this library works. All I am getting are errors:

[Vue warn]: Invalid prop: type check failed for prop "value". Expected String, got Null. 
Uncaught TypeError: Cannot read property 'match' of null
    at Document.$detectNewLine (eval at 137 (http://127.0.0.1:8081/1.js:136:1), <anonymous>:6269:25)

**Comment by dudesweet100** [comment]
Ah ok, now I see, v-model="variable"

variable cannot be null, it has to be a string.

**Comment by chairuosen** [comment]
Yeah, It should be a String.

**Comment by dudesweet100** [comment]
Hm, but I got a different issue, code editor doesnt work properly. I press enter once, it is shown as if I pressed it twice and line numbering is also wrong.

<img width="652" alt="screen shot 2016-12-05 at 17 29 30" src="https://cloud.githubusercontent.com/assets/616192/20892967/6a36b370-bb10-11e6-9e12-e6a598d484db.png">

**Comment by chairuosen** [comment]
I have no idea about this. It works fine on my mac and windows pc.
Check the css first. maybe is style confliction.

**Comment by dudesweet100** [comment]
I am using bulma + ace, maybe that could be the problem.

**Comment by chairuosen** [comment]
Create a clean demo and see if the problem reproduced.
