### ISSUE TITLE
疑点

### ISSUE THREAD

**Issue by cn-xufei** [chairuosen/vue2-ace-editor#23]
https://github.com/chairuosen/vue2-ace-editor/blob/5195cadadd9fb7013618911f328cd907aef1ded7/index.js#L49

敢问你的theme和lang所需要的js文件在哪引入？
当lang=json；theme=chrome时，theme-chrme.js----404 ;mode-json----404

**Comment by chairuosen** [comment]
自己引入，看readme

**Comment by cn-xufei** [comment]
ok，刚看到😰，那你可以直接
``` javascript
mounted () {
    ...
    require(`brace/mode/${lang}`)
    require(`brace/theme/${theme}`)
    ...
}
```

**Comment by chairuosen** [comment]
这样会打进该目录所有module，包非常大

**Comment by cn-xufei** [comment]
3Q🌹，require中的path确实不能是动态的
