### ISSUE TITLE
How can I disable the editor?

### ISSUE THREAD

**Issue by soichih** [chairuosen/vue2-ace-editor#25]
I'd like to use this ace as a syntax highlighter if user doesn't have write access to my text field. I've tried adding "disabled" attribute but didn't work. How can I make it to disable?

**Comment by chairuosen** [comment]
1.get editor instance at init event
2. editor.setReadonly(true)

**Comment by aragonet** [comment]
`<template>
    <editor ref='myEditor' v-model="data" @init="editorInit" lang="json" theme="chrome"></editor>
</template>

<script>
import Editor from "vue2-ace-editor";

export default {
  components: { Editor },
  data(){
      return {
          data: ""
      }
  },
  mounted(){
      this.$refs.myEditor.editor.setReadonly(true)
  },
  methods: {
    editorInit: function(editor) {
      require("brace/mode/json");
      require("brace/theme/chrome");
      
      editor.setReadonly(true)
    }
  }
};
</script>`

None of both ways to setReadonly works.
How can I set it to readOnly?

**Comment by chairuosen** [comment]
@aragonet Still works fine for me now.   Editor cannot input after call `editor.setReadOnly(true);`.
What does "doesn't works" mean.
Can focus? Can input?

**Comment by aragonet** [comment]
Sorry for missing error log
Error in v-on handler: "TypeError: editor.setReadonly is not a function"

**Comment by chairuosen** [comment]
what vue2-ace-editor version do you use? and brace version?

**Comment by aragonet** [comment]
"vue2-ace-editor": "0.0.13"

What do you mean by brace?

**Comment by chairuosen** [comment]
brace is one of vue2-ace-editor's dependencies. it provides the api  `setReadOnly()`.
try to add a breakpoint before `editor.setReadOnly(true)` and see what `editor` is.
`undefined` or something.  It should be an Object which is ace instance.

**Comment by aragonet** [comment]
Ok, the problem was that setReadOnly functions has a mayus O. :sweat_smile: 

Thank you very much for your help and your quickly answers!

**Comment by gxjcoo** [comment]
> @aragonet Still works fine for me now. Editor cannot input after call `editor.setReadOnly(true);`.
> What does "doesn't works" mean.
> Can focus? Can input?

Can delete
