### ISSUE TITLE
Multiple instances can cause browser to crash

### ISSUE THREAD

**Issue by jimtendo** [chairuosen/vue2-ace-editor#28]
I can't quite determine the exact behaviour here, but when multiple instances of vue2-ace-editor exist, it appears to crash the browser window. I suspect something was not being cleaned up properly.

In any case, adding the following hook has solved this for me:

```
    beforeDestroy: function() {
        this.editor.destroy();
        this.editor.container.remove();
    }
```

**Comment by chairuosen** [comment]
Thanks man. I'll do a test and fix it in next version

**Comment by chairuosen** [comment]
fixed & published
