### ISSUE TITLE
Typescript definitions?

### ISSUE THREAD

**Issue by erajasekar** [chairuosen/vue2-ace-editor#33]
The component works great, but get warnings when I try to used it from a typescript based VueJs app. Any chance you can provide typescript definitions for this npm module?

Thanks you,
Raja.

**Comment by chairuosen** [comment]
what warnings ? eslint?

**Comment by erajasekar** [comment]
```
require statement not part of an import statement
    25 |
    26 |
  > 27 |     const editor = require('vue2-ace-editor');
```
Ideally I should able to import it using ES6 syntax like `import {editor} from 'vue2-ace-editor'`. But that doesn't work in typescript without type definitions. So I am using requirejs, but that's giving me this warning. 

What is the right way to use vue2-ace-editor in typescript?

**Comment by chairuosen** [comment]
it should be `import editor from 'vue2-ace-editor` with ES6 & webpack.
you project is not based on webpack?

**Comment by erajasekar** [comment]
Thanks I was able to resolve it by create new file `vue2-ace-editor.d.ts` with content `declare module 'vue2-ace-editor'` and then import worked.
