### ISSUE TITLE
editor.undo() compatibility

### ISSUE THREAD

**Issue by neutralvibes** [chairuosen/vue2-ace-editor#37]
### Desired
When using a editor instance, if you set new content during a session, the undo history is reset.

### At present
When using a editor instance, if you switch to different content (eg loading a new file to be edited) the undo history (using Ctrl-z) will revert to the last content. 

### Suggestion
To ensure the ace undo manager is appropriately reset, use the 

> **this.editor.session.setValue**

 method instead of 

> this.editor.setValue

. 

### Fix
`    watch:{
        value:function (val) {
            if(this.contentBackup !== val){
                this.editor.session.setValue(val,1);
                this.contentBackup = val;               
            }
        },`

**Comment by chairuosen** [comment]
Thanks man. I'll check it later..  so busy these days..

**Comment by chairuosen** [comment]
fixed in 0.0.13
