### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by kz** [chairuosen/vue2-ace-editor#39]
Would it be possible for you to open source this package by choosing and adding an open source license? Currently, without a license, this code isn't open source<sup>1</sup> and more corporate GitHub users won't be able to use/modify/redistribute your codebase.

<sup>1</sup> https://choosealicense.com/no-permission/

**Comment by chairuosen** [comment]
done. thanks

**Comment by chairuosen** [comment]
@kz It's ok to change another license.
I dont want somebody modify the code and republish it as his own. Which type of license should I use?  Apache?

**Comment by kz** [comment]
Both Apache and MIT are good. Both will include your name and copyright notice.

**Comment by chairuosen** [comment]
I changed it to Apache
