### ISSUE TITLE
安装后，会有这个错误提示

### ISSUE THREAD

**Issue by luguosheng1314** [chairuosen/vue2-ace-editor#4]
This dependency was not found:

* emmet/emmet in ./~/vue2-ace-editor/index.js

我的环境是npm 4.0.5  node4.4.7
麻烦看下是怎么回事

**Comment by chairuosen** [comment]
fix, emmet库更新后换了名字，现在固定引用老版本emmet库，重新安装vue2-ace-editor@latest试试

**Comment by luguosheng1314** [comment]
谢谢
更新后 会报ace is not defined
