### ISSUE TITLE
JSRegex highlighting

### ISSUE THREAD

**Issue by boriskogan81** [chairuosen/vue2-ace-editor#41]
Hello,

I notice that Ace has a highlighting rule for [JSRegex](https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/js_regex_highlight_rules.js). I would like to implement this in my editor component, which I'd like to only accept valid Regex. How can I do this? Right now I'm doing the standard setup, with

```
                    <editor id="regexInput"
                            v-model="newRegex"
                            @init="editorInit"
                            lang="html"
                            theme="chrome"
                            width="500"
                            height="20">
                    </editor>
```
and 
```
           editorInit: function () {
                require('brace/ext/language_tools'); //language extension prerequsite...
                require('brace/mode/html');
                require('brace/mode/javascript');    //language
                require('brace/mode/less');
                require('brace/theme/chrome');
                require('brace/snippets/javascript'); //snippet
            }
```

**Comment by chairuosen** [comment]
Searched and got some answers but not tried.

1.  `var ace = require('brace');`
and define an custom highlight mode : https://medium.com/@jackub/writing-custom-ace-editor-mode-5a7aa83dbe50

2.  `editorInit: function (editor) { // got editor instance here }`
and then use `editor.getSession().setMode()` to set mode

**Comment by boriskogan81** [comment]
Actually, this core rule would work fine for me, but I can't figure out how to require it: https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/js_regex_highlight_rules.js

I've installed Ace and see it as a node module, but it doesn't have this rule. Neither does Brace. The Ace documentation says "many other languages are available as separate modules" but doesn't explain how to install them. Thoughts?

**Comment by chairuosen** [comment]
I guess :
1. copy the file js_regex_highlight_rules.js to your project.
2. Modify the first line to `var ace = require('brace'); ace.define('brace/mode/js_regex_highlight_rules',function(require, exports, module) { ...................`
3. require this file before editorInit();

**Comment by boriskogan81** [comment]
Where should I modify the first line to ```var ace = require ('brace')```?

How do I require this file? Currently, I'm doing all my requires in
editorInit, as per your documentation.

Sincerely,

Baruch

**Comment by chairuosen** [comment]
I mean the first line of js_regex_highlight_rules.js
it uses define as global which equals to window.define . but the article of medium says it should be ace.define
so you need `ace`, so require it before the code.
