### ISSUE TITLE
How can I remove the vertical line?

### ISSUE THREAD

**Issue by IronPillar-Sheng** [chairuosen/vue2-ace-editor#44]
the vertical line is always alive
`<div class="ace_print-margin" style="left: 580.1px; visibility: visible;"></div>`

**Comment by chairuosen** [comment]
This?
https://stackoverflow.com/questions/14907184/is-there-a-way-to-hide-the-vertical-ruler-in-ace-editor

**Comment by chairuosen** [comment]
`editorInit(editor){      }`

**Comment by chetanmajithiya28** [comment]
Use options props value, should object value..

`<editor v-model="content" @init="editorInit" :options="myoptions" lang="html" theme="chrome" width="500" height="100"></editor>`

`data() {
        return {
          myoptions: {
            readOnly: false,
            showPrintMargin: false, /* <---------------------------- */
            wrap: true,
            highlightActiveLine: false,
            useWorker: false,
            showFoldWidgets: false,
            fontSize: '16px',
            highlightGutterLine: false,
            wrapBehavioursEnabled: true,
            maxLines: 100,
            autoScrollEditorIntoView: true,
          }
        }
      }`
