### ISSUE TITLE
How to set the font size

### ISSUE THREAD

**Issue by mao-shonen** [chairuosen/vue2-ace-editor#49]
Ace document is
```javascrip
document.getElementById('editor').style.fontSize='12px';
```
I use
```javascrip
editorInit(editor) {
     .........
    Console.log(editor)
    document.getElementById(editor.id).style.fontSize='16px';
},
```
I can't find related content in the editor
What should I do or what I missed?

**Comment by chairuosen** [comment]
try google first
https://stackoverflow.com/questions/21900938/how-do-i-change-the-font-style-in-ace-editor
