### ISSUE TITLE
How do I select characters in a text box?

### ISSUE THREAD

**Issue by jiaqizhang77** [chairuosen/vue2-ace-editor#50]
Is there a way to get the mouse selected characters in the text box?
I haved used 'onSelectionChange' but failed. Thank you.

**Comment by chairuosen** [comment]
This is issue about ace it self.

https://stackoverflow.com/questions/23996814/how-can-i-get-selected-text-in-ace-editor

**Comment by jiaqizhang77** [comment]
> This is issue about ace it self.
> 
> https://stackoverflow.com/questions/23996814/how-can-i-get-selected-text-in-ace-editor



> This is issue about ace it self.
> 
> https://stackoverflow.com/questions/23996814/how-can-i-get-selected-text-in-ace-editor

but how I use editor.getSelectedText() in my components?

**Comment by chairuosen** [comment]
https://github.com/chairuosen/vue2-ace-editor/blob/master/README.md
How to user .  title No.5   Access the ACE's instance

**Comment by jiaqizhang77** [comment]
> https://github.com/chairuosen/vue2-ace-editor/blob/master/README.md
> How to use . title No.5 Access the ACE's instance

Thank you very much !!!

**Comment by jiaqizhang77** [comment]
I want ask more about how I can set style like input's placeholder and how to reset the editor. Thank you.

**Comment by chairuosen** [comment]
Sorry ,Theres no answer here. This is only a packaging of data binding. Plz Google `ace editor ${yourQuestion}`
