### ISSUE TITLE
Is it possible to use slots?

### ISSUE THREAD

**Issue by KevinMallinson** [chairuosen/vue2-ace-editor#52]
It would be great if we can use slots, e.g. instead of

```
<editor v-model="content" />
```

we have

```
<editor>
   function HelloWorld() {
        console.log("Hello World")
    }
</editor>
```

Is this possible to implement? 

Thanks

**Comment by chairuosen** [comment]
I think it is not possible. 
editor will/should change the text but slots can only be changed by the father component
