### ISSUE TITLE
unable to set inline:true for php code so that <?php is not required for the highlighter

### ISSUE THREAD

**Issue by gtrig** [chairuosen/vue2-ace-editor#54]
on lines 49 and 82 we need to set an object instead of 'ace/mode/'+lang
the desired effect is like this : editor.getSession().setMode({path: 'ace/mode/php', inline: true});
it could be:
editor.getSession().setMode(lang); so we could either assign 
lang = ace/mode/php or
lang = {path: 'ace/mode/php', inline: true}

**Comment by chairuosen** [comment]
added at 0.0.14
