### ISSUE TITLE
光标错位问题

### ISSUE THREAD

**Issue by fairyly** [chairuosen/vue2-ace-editor#63]
vue 中 lang="javascript" 就是输入的时候,开始好好的，往后输入光标错位越多
![image](https://user-images.githubusercontent.com/17672815/66634292-54b8c200-ec3f-11e9-9122-6e739b9de8ce.png)

**Comment by fairyly** [comment]
[brace#issue-126](https://github.com/thlorenz/brace/issues/126)

大概知道什么问题了，这个 issue 上说的是使用了非等宽字体导致的

**Comment by YRREALLYCUTE** [comment]
您好，请问您是使用了哪种字体啊？遇到了同样的问题，但是更换为等宽字体之后仍然不能解决，有光标延后或者提前的情况
