### ISSUE TITLE
Event when editor content rendered?

### ISSUE THREAD

**Issue by mike-kelly** [chairuosen/vue2-ace-editor#67]
Hi, I'm trying to calculate the positions of multiple editors in a column on a page. 

In the `mounted` hook of the parent component, the editors are not displayed. This means that the dimensions of each editor are 'wrong' because they're empty. When the text **is** displayed afterwards, successive editors are pushed further down the page into new positions.

I tried using the `v-on:input` event on the Ace Editor component. When this fires the editor body text is still not displayed. Same with `v-on:init`. Also, using `$nextTick` with these events doesn't work - the text is still not displayed at this point.

Any suggestions of how to detect when editor text is fully rendered?

**Comment by chairuosen** [comment]
It seems to be no official `ready` event of Ace Editor.
See https://github.com/ajaxorg/ace/issues/2082 and https://groups.google.com/forum/#!topic/ace-discuss/EFUiRQ6WHq0

but you can try `setTimeout(()=>{ // your code },0)` in the `init` event, I tested , it works.
