### ISSUE TITLE
How can I activate search function

### ISSUE THREAD

**Issue by OliverAndersRWE** [chairuosen/vue2-ace-editor#70]
Hi
set this up in an element.io vue project and it works perfectly.

What I'm missing is the search feature. (How) can I activate this?

Kind Regards
Oliver

**Comment by Hyperblaster** [comment]
I'm also trying to figure this out. I'm guessing it's need to be required in here somewhere
```javasript
editorInit: function () {
            require('brace/ext/language_tools') //language extension prerequsite...
            require('brace/mode/html')                
            require('brace/mode/javascript')    //language
            require('brace/mode/less')
            require('brace/theme/chrome')
            require('brace/snippets/javascript') //snippet
        }
```

**Comment by robsonalvesnogueira** [comment]
> I'm also trying to figure this out. I'm guessing it's need to be required in here somewhere
> 
> ```
> editorInit: function () {
>             require('brace/ext/language_tools') //language extension prerequsite...
>             require('brace/mode/html')                
>             require('brace/mode/javascript')    //language
>             require('brace/mode/less')
>             require('brace/theme/chrome')
>             require('brace/snippets/javascript') //snippet
>         }
> ```

Hi @Hyperblaster. I added this line to my init function and worked fine:
`require('brace/ext/searchbox')`

**Comment by OliverAndersRWE** [comment]
worked out. many thanks
