### ISSUE TITLE
Problem with handle @change in editor

### ISSUE THREAD

**Issue by jakubstankowski** [chairuosen/vue2-ace-editor#75]
Hi!

I have problem with handle change on this editor, it's not working and not get any value this is my code:

` <editor
                        ref='myEditor'
                        :value="returnJsonFromDATA"
                        @init="editorInit"
                        @change="update"
                        lang="javascript"
                        theme="chrome"
                        width="100%"
                        height="60vh"/>`

I know if is possible to handle change with @input, but it's not good solution because i send to many request, show to many error etc

Better way is using @change, it is possible to improve this funcionality in this great library ? 

Thanks for response!

**Comment by chairuosen** [comment]
input event is same as change event.   your problem is it fires too often?  try google
 js debounce
