### ISSUE TITLE
有什么好的办法可以修改编辑器的警告提示吗？

### ISSUE THREAD

**Issue by MangoTsing** [chairuosen/vue2-ace-editor#76]
想增加或修改左侧警告规则。

目前有个需求，想在代码出现document. window对象等时候给一个合理的报错提示。

另外想问一下有没有办法可以添加 css , js 的语法补全提示，虽然可以自定义补全，但是纯手写也太难了...有方便的插件吗？

谢谢。

**Comment by chairuosen** [comment]
这方面需求得查阅ace相关资料，配合readme第五条访问到ace实例来做第三方修改与控制
