### ISSUE TITLE
uni-app中引用出不来效果怎么办呢

### ISSUE THREAD

**Issue by wangshengli0421** [chairuosen/vue2-ace-editor#94]
<template>
	<editor v-model="title" @init="editorInit" lang="html" theme="chrome" width="500px" height="100"></editor>
</template>

<script>
	export default {
		 components: {
		    editor: require('vue2-ace-editor'),
		},
		data() {
			return {
				title: 'Hello'
			}
		},
		onLoad() {
			
		},
		methods: {
			editorInit: function () {
				require('brace/ext/language_tools') //language extension prerequsite...
				require('brace/mode/html')                
				require('brace/mode/javascript')    //language
				require('brace/mode/less')
				require('brace/theme/chrome')
				require('brace/snippets/javascript') //snippet
				console.log('初始化')
			}
		}
	}
</script>

<style>
	.content {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
	}

	.logo {
		height: 200rpx;
		width: 200rpx;
		margin-top: 200rpx;
		margin-left: auto;
		margin-right: auto;
		margin-bottom: 50rpx;
	}

	.text-area {
		display: flex;
		justify-content: center;
	}

	.title {
		font-size: 36rpx;
		color: #8f8f94;
	}
</style>

![image](https://user-images.githubusercontent.com/100948785/212669317-dc7c427a-e162-4d2f-a4bb-9d256070632e.png)

**Comment by chairuosen** [comment]
ace-edito一开始是基于dom的，也许并不适配uni-app，以及小程序，我并没有测试过。
